### ISSUE TITLE
ERROR! Failed to start Elixir. when enabling rabbitmq_management

### ISSUE THREAD

**Issue by codrin-kruijne** [rabbitmq/erlang-rpm#102] opened 2022-05-20 10:17 UTC
Hi there,

I am new to raising issues on GitHub, so please let me know if you need more information. I successfully installed your erlang and rabbitmq-server (on Oracle Linux 8, which is RedHat/CentoOS compatible), but it seems something is off in your latest erlang release when I try to enable the rabbitmq_management plugin (I did not have this issue in the previous release):

Please see command and error below:
===

Installed:
  rabbitmq-server-3.10.1-1.el8.noarch

Complete!
[opc@instance20220520091027 ~]$ sudo rabbitmq-plugins enable rabbitmq_management
=ERROR REPORT==== 20-May-2022::09:38:48.316793 ===
beam/beam_load.c(551): Error loading function elixir:start/2: op put_tuple u x:
  please re-compile this module with an Erlang/OTP 25 compiler

=ERROR REPORT==== 20-May-2022::09:38:48.316817 ===
Loading of /usr/lib/rabbitmq/lib/rabbitmq_server-3.10.1/escript/rabbitmq-plugins/elixir.beam failed: badfile

=CRASH REPORT==== 20-May-2022::09:38:48.316943 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.81.0>
    registered_name: []
    exception exit: {bad_return,
                        {{elixir,start,[normal,[]]},
                         {'EXIT',
                             {undef,
                                 [{elixir,start,[normal,[]],[]},
                                  {application_master,start_it_old,4,
                                      [{file,"application_master.erl"},
                                       {line,293}]}]}}}}
      in function  application_master:init/4 (application_master.erl, line 142)
    ancestors: [<0.80.0>]
    message_queue_len: 1
    messages: [{'EXIT',<0.82.0>,normal}]
    links: [<0.80.0>,<0.44.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 233
    stack_size: 28
    reductions: 174
  neighbours:

=INFO REPORT==== 20-May-2022::09:38:48.349798 ===
    application: elixir
    exited: {bad_return,
                {{elixir,start,[normal,[]]},
                 {'EXIT',
                     {undef,
                         [{elixir,start,[normal,[]],[]},
                          {application_master,start_it_old,4,
                              [{file,"application_master.erl"},
                               {line,293}]}]}}}}
    type: temporary

=INFO REPORT==== 20-May-2022::09:38:48.349916 ===
    application: compiler
    exited: stopped
    type: temporary

ERROR! Failed to start Elixir.
error: {error,
           {elixir,
               {bad_return,
                   {{elixir,start,[normal,[]]},
                    {'EXIT',
                        {undef,
                            [{elixir,start,[normal,[]],[]},
                             {application_master,start_it_old,4,
                                 [{file,"application_master.erl"},
                                  {line,293}]}]}}}}}}

**Comment by michaelklishin** [comment] 2022-05-20 10:28
Duplicate of https://github.com/rabbitmq/rabbitmq-server/discussions/4867. RabbitMQ `3.10.2` and `3.9.18` will be produced using Elixir built on Erlang 23.

**Closed** 2022-05-20 10:27 UTC
